export const Topics = [
    "Technology & AI",
    "Science & Innovation",
    "Business & Finance",
    "Education & Learning",
    "Health & Wellness",
    "Society & Culture",
    "History & Geopolitics",
    "Environmental Topics",
    "Personal Development & Productivity",
    "Fun & Curiosity"
];

export const Ideas = [
    "The Future of Artificial Intelligence in Everyday Life",
    "How AI is Revolutionizing Healthcare",
    "The Role of AI in Cybersecurity",
    "Ethical Concerns in Artificial Intelligence Development",
    "AI in Space Exploration: The Next Frontier",
    "The Rise of AI-Powered Virtual Assistants",
    "Machine Learning vs. Deep Learning: Key Differences",
    "AI and the Future of Self-Driving Cars",
    "The Impact of AI on Traditional Jobs and Employment",
    "How AI is Transforming Digital Marketing",
    "The Role of AI in Climate Change Research",
    "Quantum Computing: The Future of Supercomputers",
    "How Biotechnology is Shaping the Future",
    "Exploring the Mysteries of Black Holes",
    "The Search for Extraterrestrial Life Using AI",
    "Renewable Energy Technologies: The Next Big Leap",
    "The Science Behind Genetically Modified Organisms (GMOs)",
    "Nanotechnology: What It Means for the Future",
    "CRISPR and the Future of Genetic Engineering",
    "Smart Materials: Shaping the Future of Construction",
    "AI in Financial Forecasting and Stock Market Predictions",
    "How Cryptocurrencies Are Changing Global Finance",
    "The Rise of Digital Payments and Cashless Societies",
    "The Future of E-Commerce with AI and Automation",
    "How AI is Enhancing Fraud Detection in Banking",
    "The Role of Big Data in Business Decision Making",
    "Understanding Decentralized Finance (DeFi)",
    "The Impact of AI on the Gig Economy",
    "Future-Proofing Businesses with AI",
    "Emerging Startups Leveraging AI for Growth",
    "AI-Powered Personalized Learning: The Future of Education",
    "How Augmented Reality is Transforming Classrooms",
    "The Rise of Online Learning and Virtual Universities",
    "The Future of Education: Human Teachers vs. AI",
    "The Role of Gamification in Learning",
    "AI Tutors: Will They Replace Human Educators?",
    "How AI Can Improve Special Education",
    "The Benefits of Coding Education for Kids",
    "Learning a New Language with AI-Powered Tools",
    "How Blockchain Can Revolutionize Academic Credentials",
    "AI in Mental Health: Chatbots and Virtual Therapists",
    "Wearable Technology for Health and Fitness",
    "AI in Drug Discovery and Disease Prediction",
    "The Role of AI in Personalized Medicine",
    "How AI Can Improve Elderly Care",
    "The Impact of AI on Medical Diagnosis",
    "How Telemedicine is Changing Healthcare Access",
    "The Future of Robotic Surgery",
    "AI and Nutrition: Personalized Diet Plans",
    "Using AI for Stress Management and Mindfulness",
    "The Influence of AI on Music and Art",
    "How AI is Changing the Film and Entertainment Industry",
    "Social Media Algorithms: How They Shape Public Opinion",
    "AI and Fake News: The Challenge of Misinformation",
    "The Impact of AI on Journalism and News Reporting",
    "AI-Generated Influencers and Virtual Celebrities",
    "The Future of Online Dating with AI Matchmaking",
    "How AI is Transforming the Fashion Industry",
    "AI in Sports Analytics and Player Performance",
    "AI and Ethics: Can Machines Be Fair?",
    "The Role of AI in Military Strategy and Defense",
    "How AI is Changing International Diplomacy",
    "The Geopolitics of AI Superpowers: US vs. China",
    "AI and National Security: Risks and Benefits",
    "The Impact of AI on Surveillance and Privacy",
    "The History of AI: From Turing to Modern AI",
    "AI in Space Exploration: Colonizing Other Planets",
    "The Future of Smart Cities with AI",
    "AI in Law Enforcement: Benefits and Concerns",
    "AI in the Criminal Justice System: Fair or Biased?",
    "AI for Climate Change Mitigation and Adaptation",
    "Smart Agriculture: How AI is Helping Farmers",
    "AI in Wildlife Conservation and Animal Protection",
    "The Role of AI in Disaster Prediction and Management",
    "How AI Can Help Reduce Carbon Emissions",
    "AI in Renewable Energy Optimization",
    "The Future of Smart Forests and AI Monitoring",
    "AI in Ocean Exploration and Marine Conservation",
    "How AI Can Improve Waste Management and Recycling",
    "Using AI to Combat Deforestation",
    "How AI Can Help Improve Productivity",
    "AI in Personal Finance Management",
    "AI-Powered Goal Setting and Habit Tracking",
    "The Role of AI in Time Management",
    "AI-Generated Writing Assistants: Are They Effective?",
    "AI in Career Development and Job Searching",
    "The Future of Work: AI and Remote Work Trends",
    "AI in Customer Service and Chatbot Assistants",
    "AI in Resume Screening and Job Recruitment",
    "How AI Can Improve Public Speaking Skills",
    "AI-Generated Poetry and Creative Writing",
    "Can AI Predict the Future of Human Evolution?",
    "How AI is Changing Video Game Development",
    "AI in Astrology and Fortune-Telling: Myth or Reality?",
    "AI and Paranormal Research: Can It Detect Ghosts?",
    "AI-Generated Jokes: Can Machines Be Funny?",
    "AI in Board Games and Strategy Planning",
    "The Future of AI Companions: Can Robots Be Friends?",
    "AI-Powered Cooking: Personalized Recipes and Meal Planning",
    "How AI is Changing the Way We Travel",
]